In [1]:
# Run this cell to install the required package
!pip install pyreadstat

# Then import all libraries you will need
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries loaded!")

Requirement already satisfied: pyreadstat in c:\users\eric.niyitanga\appdata\local\anaconda3\lib\site-packages (1.3.3)
Requirement already satisfied: narwhals>=2.10.1 in c:\users\eric.niyitanga\appdata\local\anaconda3\lib\site-packages (from pyreadstat) (2.18.1)
Requirement already satisfied: numpy in c:\users\eric.niyitanga\appdata\local\anaconda3\lib\site-packages (from pyreadstat) (2.3.5)
All libraries loaded!

In [2]:
# Run this cell first — it opens a file picker
from google.colab import files

uploaded = files.upload()
# → Upload both:
#    2_CFSVA18_DB_ChildAndMother_Full_.sav  ← start here
#    1_CFSVA18_DB_HouseholdQues_Full_.sav

ModuleNotFoundError: No module named 'google.colab'

In [4]:
# Load the Child and Mother dataset
df_child = pd.read_spss('2_CFSVA18_DB_ChildAndMother_Full_Annex_201904_NISR.sav')

# Quick check
print("Shape:", df_child.shape)       # rows x columns
print("Columns:", df_child.columns.tolist())
df_child.head()                        # see first 5 rows

Shape: (6736, 219)
Columns: ['PARENT_KEY', 'WOMAN_KEY', 'CHILD_KEY', 'S0_B_DATE', 'All_Sample', 'S0_C_Prov', 'S0_D_Dist', 'UrbanRural', 'WI_cat', 'Ubudehe', 'S0_E_Livezone', 'FS_final', 'livelihood_group', 'HHSize_cat', 'S1_01_3', 'Age_HeadHH', 'S1_01_4', 'VHHSize', 'VSampleSize', 'FinalWeight', 'TotDistHHs', 'S1_01', 'S14_01', 'S14_01_3', 'S14_01_4', 'S14_01_4_CAT', 'S14_01_5', 'S14_02', 'S14_03', 'S14_04', 'S14_05', 'S14_06', 'S14_07', 'S14_08', 'S14_09', 'S14_10', 'S14_11', 'S14_11_2', 'S14_11_2_SMT_1', 'S14_11_2_SMT_2', 'S14_11_2_SMT_3', 'S14_11_2_SMT_4', 'S14_11_2_SMT_5', 'S14_11_2_SMT_6', 'S14_11_2_SMT_7', 'S14_11_2_SMT_8', 'S14_11_2_SMT_88', 'S14_11_2_2', 'S14_12', 'S14_13', 'S14_14', 'AS14_15', 'AS14_15_2', 'AS14_15_3', 'BS14_15', 'CS14_15', 'CS14_15_2', 'DS14_15', 'DS14_15_2', 'ES14_15', 'FS14_15', 'GS14_15', 'GS14_15_2', 'HS14_15', 'HS14_15_2', 'IS14_15', 'JS14_15', 'KS14_15', 'LS14_15', 'MS14_15', 'AS14_16', 'BS14_16', 'CS14_16', 'DS14_16', 'ES14_16', 'FS14_16', 'GS14_16', 'HS14_16', 'IS14_16', 'JS14_16', 'KS14_16', 'LS14_16', 'MS14_16', 'NS14_16', 'OS14_16', 'PS14_16', 'QS14_16', 'RS14_16', 'S14_17', 'S14_18', 'S14_19', 'S14_19_2', 'S14_20', 'S14_20_SMT_0', 'S14_20_SMT_1', 'S14_20_SMT_2', 'S14_20_SMT_3', 'S14_20_SMT_4', 'ENA_SURVDATE', 'ENA_DOB', 'ENA_DOBM', 'ENA_WEIGHT', 'ENA_HEIGHT', 'E0A_EDEMA', 'ENA_MUAC', 'WAZ_NCHS', 'HAZ_NCHS', 'WHZ_NCHS', 'WAZ_WHO', 'HAZ_WHO', 'WHZ_WHO', 'BMIZ_WHO', 'WAM_NCHS', 'HAM_NCHS', 'WHM_NCHS', 'Flag_NCHS', 'Flag_WHO', 'MUACZ_age', 'Height_Age_WHO', 'MUACZ_Ht', 'Age_cat_child', 'Age_6_59_5cat', 'AgeCat', 'MAD_FBF1_V01', 'MAD_FBF1_V02', 'MAD_FBF1_V03', 'MAD_FBF1_V04', 'MAD_FBF1_V05', 'MAD_FBF1_V06', 'MAD_FBF1_V07', 'MAD_FBF1_V08', 'MAD_FBF1_V09', 'MAD_FBF1_CDDS', 'MAD_FBF1_CMMFS', 'MAD_FBF1_CMAD', 'MAD_FBF4_V01', 'MAD_FBF4_V02', 'MAD_FBF4_V03', 'MAD_FBF4_V04', 'MAD_FBF4_V05', 'MAD_FBF4_V06', 'MAD_FBF4_V07', 'MAD_FBF4_V08', 'MAD_FBF4_V09', 'MAD_FBF4_CDDS', 'MAD_FBF4_CMMFS', 'MAD_FBF4_CMAD', 'WAZ_WHO_Cat', 'WHZ_WHO_Cat', 'HAZ_WHO_Cat', 'Global_Stunting', 'Global_Wasting', 'Global_Underweight', 'Separator_Two', 'Spliter_Two', 'S13_01_3', 'S13_01_4', 'S13_01_5', 'S13_02', 'S13_03', 'S13_03_2', 'S13_03_3', 'S13_04', 'S13_05', 'S13_05_2', 'S13_06', 'S13_07', 'S13_08', 'S13_08_2', 'S13_08_3', 'S13_09', 'S13_10', 'S13_10_2', 'S13_11', 'S13_11_2', 'S13_12', 'S13_13', 'S13_13_2', 'S13_14', 'S13_14_SMT_1', 'S13_14_SMT_2', 'S13_14_SMT_3', 'S13_14_SMT_4', 'S13_14_SMT_5', 'S13_14_SMT_6', 'S13_14_SMT_88', 'S13_14_2', 'S13_15', 'S13_16', 'Muac_cat', 'AS13_17', 'BS13_17', 'CS13_17', 'DS13_17', 'ES13_17', 'GS13_17', 'HS13_17', 'IS13_17', 'JS13_17', 'KS13_17', 'LS13_17', 'MS13_17', 'NS13_17', 'OS13_17', 'PS13_17', 'QS13_17', 'Cereals_MDDW', 'Pulses_MDDW', 'Nuts_MDDW', 'Milk_MDDW', 'Meat_MDDW', 'Eggs_MDDW', 'GreenVeg_MDDW', 'VitA_MDDW', 'OtherVeg_MDDW', 'OtherFruit_MDDW', 'Tot_MDDW', 'MDDWLess5', 'Age_cat_child_REC']

,PARENT_KEY,WOMAN_KEY,CHILD_KEY,S0_B_DATE,All_Sample,S0_C_Prov,S0_D_Dist,UrbanRural,WI_cat,Ubudehe,...,Milk_MDDW,Meat_MDDW,Eggs_MDDW,GreenVeg_MDDW,VitA_MDDW,OtherVeg_MDDW,OtherFruit_MDDW,Tot_MDDW,MDDWLess5,Age_cat_child_REC
0,uuid:bdaebd67-fe09-447d-b7fb-62da38a360e7,Doesn't live in this household,uuid:bdaebd67-fe09-447d-b7fb-62da38a360e7/HHG1...,1.374123e+10,Rwanda,Northern province,Gakenke,Rural,Wealthy,[3] Category three,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24-59 months
1,uuid:7cabec6c-9227-46e1-bea8-b5d8e3c27949,uuid:7cabec6c-9227-46e1-bea8-b5d8e3c27949/HHG1...,uuid:7cabec6c-9227-46e1-bea8-b5d8e3c27949/HHG1...,1.374123e+10,Rwanda,Eastern province,Kayonza,Rural,Poor,[2] Category two,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,<5 food groups,24-59 months
2,uuid:d1a18419-7254-431c-a073-d7a2ec5a9087,uuid:d1a18419-7254-431c-a073-d7a2ec5a9087/HHG1...,uuid:d1a18419-7254-431c-a073-d7a2ec5a9087/HHG1...,1.374149e+10,Rwanda,Southern province,Ruhango,Rural,Poorest,[3] Category three,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,<5 food groups,24-59 months
3,uuid:ec1919a8-1ac3-4383-9729-1836a4afaaf9,uuid:ec1919a8-1ac3-4383-9729-1836a4afaaf9/HHG1...,uuid:ec1919a8-1ac3-4383-9729-1836a4afaaf9/HHG1...,1.374062e+10,Rwanda,Western province,Nyamasheke,Rural,Medium,[1] Category one,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0,<5 food groups,24-59 months
4,uuid:bfdb854b-16c6-44ba-b9ac-dba68ec099a6,uuid:bfdb854b-16c6-44ba-b9ac-dba68ec099a6/HHG1...,uuid:bfdb854b-16c6-44ba-b9ac-dba68ec099a6/HHG1...,1.373950e+10,Rwanda,Southern province,Kamonyi,Rural,Wealthy,[3] Category three,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,<5 food groups,24-59 months

In [5]:
# Load the Household dataset
df_house = pd.read_spss('1_CFSVA18_DB_HouseholdQues_Full_Annex_201904_NISR.sav')

# Quick check
print("Shape:", df_house.shape)
print("Columns:", df_house.columns.tolist())
df_house.head()

Shape: (9709, 343)
Columns: ['VHHSize', 'VSampleSize', 'TotDistHHs', 'FinalWeight', 'PARENT_KEY', 'LYR01', 'All_Sample', 'UrbanRural', 'S0_C_Prov', 'S0_D_Dist', 'S0_E_Livezone', 'Ubudehe', 'WI_cat_lyr', 'FS_final_lyr', 'BRK01', 'S1_01_3', 'S1_01_4', 'Age_HeadHH', 'S1_01_7', 'S1_01_8', 'S1_01_9', 'S1_01_10', 'S1_01_11', 'Nb_spouse', 'S1_01_15_2', 'S1_01_16', 'S1_01_16_2', 'S1_01_17', 'S1N11', 'S1_01', 'HHSize_cat', 'S1C03', 'S1C02', 'S2_02', 'S2_03', 'S2_05', 'S2_06', 'BRK02', 'S2_07', 'S2_07_2', 'S2_07_3', 'S2_08', 'S2_09', 'S2_09_SMT_3', 'S2_09_SMT_4', 'S2_09_SMT_1', 'S2_09_SMT_7', 'S2_09_SMT_2', 'S2_09_SMT_5', 'S2_09_SMT_6', 'S2_10', 'S2_10_2', 'S2_10_3', 'S2_10_4', 'S2_11', 'S2_11_2', 'S2_11_3', 'S2_11_4', 'S2_11_5', 'S2_12', 'S2_13', 'BRK03', 'S3_05', 'LiveAct', 'livelihood_group', 'WI_cat', 'S4N1', 'S4_01', 'S4_01_2', 'S4_02_1', 'S4_02_2', 'S4_02_3', 'S4_02_4', 'No_agri_practice', 'S4_03', 'S4_03_2', 'S4_03_3', 'S4_04_SMT_1', 'S4_04_SMT_2', 'S4_04_SMT_3', 'S4_04_SMT_4', 'S4_04_SMT_5', 'S4_04_SMT_6', 'S4_04_SMT_7', 'S4_04_SMT_8', 'S4_04_SMT_9', 'S4_04_SMT_10', 'S4_04_SMT_11', 'S4_04_SMT_12', 'S4_04_SMT_13', 'S4_04_SMT_14', 'S4_04_SMT_15', 'S4_04_SMT_16', 'S4_04_SMT_17', 'S4_04_SMT_18', 'S4_04_SMT_19', 'S4_04_SMT_20', 'S4_04_SMT_21', 'S4_04_SMT_22', 'S4N2', 'S4_05_SMT_1', 'AS4_06', 'AS4_06_3', 'S4_05_SMT_2', 'BS4_06', 'BS4_06_3', 'S4_05_SMT_5', 'ES4_06', 'ES4_06_3', 'S4_05_SMT_3', 'CS4_06', 'CS4_06_3', 'S4_05_SMT_4', 'DS4_06', 'DS4_06_3', 'S4_05_SMT_7', 'GS4_06', 'GS4_06_3', 'S4_05_SMT_6', 'FS4_06', 'FS4_06_3', 'S4N3', 'S4_07', 'S4_08_2', 'S4_09', 'S4_09_SMT_1', 'S4_09_SMT_2', 'S4_09_SMT_3', 'S4_09_SMT_4', 'S4_09_SMT_5', 'S4_09_2_SMT_1', 'S4_09_2_SMT_2', 'S4_09_2_SMT_3', 'S4_09_2_SMT_4', 'S4_09_2_SMT_5', 'S4_09_2', 'S4_09_3', 'S5N1', 'S5_01_2', 'AS5_02', 'AS5_03', 'AS5_04', 'AS5_04_2', 'AS5_04_2_2', 'AS5_04_3', 'AS5_04_3_2', 'AS5_04_3_2_3', 'AS5_04_4', 'AS5_04_5', 'AS5_04_6', 'AS5_04_7', 'AS5_05', 'AS5_05_2', 'AS5_05_3', 'S5_01_3', 'BS5_02', 'BS5_03', 'BS5_04', 'BS5_04_2', 'BS5_04_2_2', 'BS5_04_3', 'BS5_04_3_2', 'BS5_04_3_2_3', 'BS5_04_4', 'BS5_04_5', 'BS5_04_6', 'BS5_04_7', 'BS5_05', 'BS5_05_2', 'BS5_05_3', 'S5_01_4', 'CS5_02', 'CS5_03', 'CS5_04', 'CS5_04_2', 'CS5_04_2_2', 'CS5_04_3', 'CS5_04_3_2', 'CS5_04_3_2_3', 'CS5_04_4', 'CS5_04_5', 'CS5_04_6', 'CS5_04_7', 'CS5_05', 'CS5_05_2', 'CS5_05_3', 'S5N4', 'S5_03', 'S5_03_2', 'S5_03_3', 'S5_04', 'S5_05', 'S5_06', 'S6N1', 'S6_01', 'S6_02', 'S6_03', 'S6_03_2', 'S6_04', 'S6_04_SMT_2', 'S6_04_SMT_1', 'S6_04_SMT_6', 'S6_04_SMT_3', 'S6_04_SMT_10', 'S6_04_SMT_5', 'S6_04_SMT_8', 'S6_04_SMT_12', 'S6_04_SMT_7', 'S6_04_SMT_4', 'S6_04_SMT_11', 'S6_04_SMT_9', 'S6N2', 'S6_04_4', 'S6_04_3', 'S6_04_5', 'S7N1', 'FIE', 'NFIE', 'T_EXP', 'S_FIE', 'share_exp_cat', 'S_NFIE', 'An_HH_EXP', 'AnPerCap_EXP', 'below_poverty_line', 'S8N2', 'S8_01', 'S8_01_2', 'S8_01_3', 'S8_02', 'S8_02_2', 'S8_02_3', 'Starch', 'Pulses', 'Milk', 'Meat', 'Vegetables', 'Fruit', 'Oil', 'Sugar', 'FCS', 'FCG', 'FG_VitACat', 'FG_ProteinCat', 'FG_HIronCat', 'DDS', 'GDDS', 'HDDSLess4', 'FS_final', 'chronically_FS', 'shr_own', 'shr_fishHun', 'shr_loan', 'shr_purcash', 'shr_purcredit', 'shr_begging', 'shr_exchange', 'shr_gift', 'shr_aid', 'S9N1', 'S9_01', 'S9_01_2', 'S9_01_2_2', 'S9_01_2_3', 'S9_01_3', 'S9N2', 'AS9_02_2', 'BS9_02_2', 'CS9_02_2', 'DS9_02_2', 'ES9_02_2', 'CSI', 'S9N4', 'stress_coping', 'crisis_coping', 'emergency_coping', 'Max_coping_behaviour', 'S11N1', 'S11_01', 'S11_01_2', 'S11_01_3', 'S11_02', 'S11N2', 'AS11_05', 'AS11_05_2', 'AS11_05_3', 'AS11_05_5', 'BS11_05', 'BS11_05_2', 'BS11_05_3', 'BS11_05_5', 'CS11_05', 'CS11_05_2', 'CS11_05_3', 'CS11_05_5', 'S12N1', 'S12_01', 'S12_03_all_assis', 'S12_03', 'S12_04_SMT_1', 'S12_04_SMT_2', 'S12_04_SMT_3', 'S12_04_SMT_4', 'S12_04_SMT_5', 'AS12_04_3', 'BS12_04_3', 'CS12_04_3', 'DS12_04_3', 'ES12_04_3', 'S12_05', 'S12_05_SMT_2', 'S12_05_SMT_5', 'S12_05_SMT_1', 'S12_05_SMT_3', 'S12_05_SMT_4', 'S12_05_SMT_6', 'S12_06', 'S12_07_SMT_1', 'S12_07_SMT_2', 'S12_07_SMT_3', 'S12_07_SMT_4', 'S12_07_SMT_5', 'S12_07_SMT_6', 'S12_07_SMT_7', 'S12_07_SMT_8', 'S12_07_SMT_9', 'S12_07_SMT_10', 'S12_07_SMT_11', 'S12_07_SMT_12', 'S12_07_SMT_13', 'AS12_07_3', 'BS12_07_3', 'CS12_07_3', 'DS12_07_3', 'ES12_07_3', 'FS12_07_3', 'HS12_07_3', 'IS12_07_3', 'JS12_07_3', 'KS12_07_3', 'LS12_07_3', 'MS12_07_3', 'FS_final_lyr_2CAT']

,VHHSize,VSampleSize,TotDistHHs,FinalWeight,PARENT_KEY,LYR01,All_Sample,UrbanRural,S0_C_Prov,S0_D_Dist,...,DS12_07_3,ES12_07_3,FS12_07_3,HS12_07_3,IS12_07_3,JS12_07_3,KS12_07_3,LS12_07_3,MS12_07_3,FS_final_lyr_2CAT
0,83.0,10.0,1524.181693,152.418169,uuid:674f7c8d-fec0-4da3-a4f5-556e41825b6e,,Rwanda,Rural,Western province,Karongi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Food Secure
1,140.0,10.0,2235.658173,223.565817,uuid:6d4dbca4-9a73-4029-be2f-699c2d65db8c,,Rwanda,Rural,Northern province,Rulindo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Food Secure
2,125.0,10.0,4180.021836,418.002184,uuid:205acfc7-6e51-4c47-8524-31945bc91745,,Rwanda,Rural,Northern province,Gicumbi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Food Secure
3,149.0,10.0,4224.365403,422.436540,uuid:22b2a07b-fdc1-4df5-8d42-b0b1018e18e1,,Rwanda,Rural,Northern province,Gicumbi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Food insecure
4,149.0,10.0,2625.957395,262.595739,uuid:e2b83c40-91b7-4227-935a-4bce62e5e59f,,Rwanda,Urban,Northern province,Gicumbi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Food Secure

In [6]:
# Run this to see your most important columns
key_cols = [
    # Target variable (what you want to predict)
    'HAZ', 'WAZ', 'WHZ',          # nutrition scores

    # Child factors
    'UrbanRural',                  # urban or rural
    'S0_C_Prov',                   # province
    'WI_cat',                      # wealth category

    # Will come from household after merge
    'VHHSize',                     # household size
    'FinalWeight',                 # survey weight
]

# Check which ones exist
found = [c for c in key_cols if c in df_child.columns or c in df_house.columns]
print("Key columns found:", found)

# Preview them
df_child[['UrbanRural','S0_C_Prov','WI_cat']].value_counts().head(10)

Key columns found: ['UrbanRural', 'S0_C_Prov', 'WI_cat', 'VHHSize', 'FinalWeight']

UrbanRural  S0_C_Prov          WI_cat
Rural       Southern province  Poorest       496
Urban       Kigali city        Wealthiest    490
Rural       Eastern province   Medium        449
            Western province   Poor          405
            Southern province  Poor          396
            Eastern province   Poor          361
            Western province   Poorest       360
            Eastern province   Wealthy       330
            Northern province  Medium        321
            Western province   Medium        313
Name: count, dtype: int64

In [7]:
# Step 1: Find ALL nutrition/anthropometry columns
nutri_cols = [c for c in df_child.columns
              if any(x in c.lower() for x in
              ['haz','waz','whz','muac','stunt','wast','underw','nutri','zscor','anthro'])]

print(f"Found {len(nutri_cols)} nutrition columns:\n")
for col in nutri_cols:
    non_null = df_child[col].notna().sum()
    print(f"  {col:30s} | non-null: {non_null} | sample: {df_child[col].dropna().unique()[:4]}")

Found 16 nutrition columns:

  ENA_MUAC                       | non-null: 5910 | sample: [158. 164. 153. 144.]
  WAZ_NCHS                       | non-null: 5910 | sample: [ 0.384 -0.81  -0.861 -1.324]
  HAZ_NCHS                       | non-null: 5910 | sample: [ 0.427 -1.782 -1.533 -0.983]
  WHZ_NCHS                       | non-null: 5910 | sample: [ 0.173  0.36   0.121 -0.932]
  WAZ_WHO                        | non-null: 5910 | sample: [ 0.489 -0.852 -0.896 -1.305]
  HAZ_WHO                        | non-null: 5910 | sample: [ 0.415 -1.876 -1.644 -1.133]
  WHZ_WHO                        | non-null: 5910 | sample: [ 0.226  0.506  0.21  -0.944]
  MUACZ_age                      | non-null: 5909 | sample: [-0.694 -0.292 -1.042 -1.635]
  MUACZ_Ht                       | non-null: 5855 | sample: [-0.192  0.172 -0.751 -1.336]
  WAZ_WHO_Cat                    | non-null: 5910 | sample: ['Normal', 'Severe', 'Moderate']
Categories (3, object): ['Moderate', 'Normal', 'Severe']
  WHZ_WHO_Cat                    | non-null: 5910 | sample: ['Normal', 'Moderate', 'Severe']
Categories (3, object): ['Moderate', 'Normal', 'Severe']
  HAZ_WHO_Cat                    | non-null: 5910 | sample: ['Normal', 'Moderate', 'Severe']
Categories (3, object): ['Moderate', 'Normal', 'Severe']
  Global_Stunting                | non-null: 5910 | sample: ['No stunted', 'Stunted']
Categories (2, object): ['No stunted', 'Stunted']
  Global_Wasting                 | non-null: 5910 | sample: ['No wasted', 'Wasted']
Categories (2, object): ['No wasted', 'Wasted']
  Global_Underweight             | non-null: 5910 | sample: ['No underweight', 'Underweight']
Categories (2, object): ['No underweight', 'Underweight']
  Muac_cat                       | non-null: 5842 | sample: ['210-230 cm', '>230 cm', '<210cm']
Categories (3, object): ['210-230 cm', '<210cm', '>230 cm']

In [8]:
# ============================================
# STEP 4: Find more child-level feature columns
# ============================================
# Search for age, sex, feeding, health columns
extra_cols = [c for c in df_child.columns
              if any(x in c.lower() for x in
              ['age','sex','gender','feed','breast','diet','water',
               'toilet','health','vacc','diarr','fever'])]

print(f"Found {len(extra_cols)} potential feature columns:")
for col in extra_cols:
    print(f"  {col:35s} | nulls: {df_child[col].isna().sum()}")

Found 7 potential feature columns:
  Age_HeadHH                          | nulls: 0
  MUACZ_age                           | nulls: 827
  Height_Age_WHO                      | nulls: 826
  Age_cat_child                       | nulls: 1013
  Age_6_59_5cat                       | nulls: 1013
  AgeCat                              | nulls: 4696
  Age_cat_child_REC                   | nulls: 0

In [9]:
# Print ALL columns with their index number
print("ALL COLUMNS IN df_child:\n")
for i, col in enumerate(df_child.columns):
    print(f"  {i:3d}. {col}")

ALL COLUMNS IN df_child:

    0. PARENT_KEY
    1. WOMAN_KEY
    2. CHILD_KEY
    3. S0_B_DATE
    4. All_Sample
    5. S0_C_Prov
    6. S0_D_Dist
    7. UrbanRural
    8. WI_cat
    9. Ubudehe
   10. S0_E_Livezone
   11. FS_final
   12. livelihood_group
   13. HHSize_cat
   14. S1_01_3
   15. Age_HeadHH
   16. S1_01_4
   17. VHHSize
   18. VSampleSize
   19. FinalWeight
   20. TotDistHHs
   21. S1_01
   22. S14_01
   23. S14_01_3
   24. S14_01_4
   25. S14_01_4_CAT
   26. S14_01_5
   27. S14_02
   28. S14_03
   29. S14_04
   30. S14_05
   31. S14_06
   32. S14_07
   33. S14_08
   34. S14_09
   35. S14_10
   36. S14_11
   37. S14_11_2
   38. S14_11_2_SMT_1
   39. S14_11_2_SMT_2
   40. S14_11_2_SMT_3
   41. S14_11_2_SMT_4
   42. S14_11_2_SMT_5
   43. S14_11_2_SMT_6
   44. S14_11_2_SMT_7
   45. S14_11_2_SMT_8
   46. S14_11_2_SMT_88
   47. S14_11_2_2
   48. S14_12
   49. S14_13
   50. S14_14
   51. AS14_15
   52. AS14_15_2
   53. AS14_15_3
   54. BS14_15
   55. CS14_15
   56. CS14_15_2
   57. DS14_15
   58. DS14_15_2
   59. ES14_15
   60. FS14_15
   61. GS14_15
   62. GS14_15_2
   63. HS14_15
   64. HS14_15_2
   65. IS14_15
   66. JS14_15
   67. KS14_15
   68. LS14_15
   69. MS14_15
   70. AS14_16
   71. BS14_16
   72. CS14_16
   73. DS14_16
   74. ES14_16
   75. FS14_16
   76. GS14_16
   77. HS14_16
   78. IS14_16
   79. JS14_16
   80. KS14_16
   81. LS14_16
   82. MS14_16
   83. NS14_16
   84. OS14_16
   85. PS14_16
   86. QS14_16
   87. RS14_16
   88. S14_17
   89. S14_18
   90. S14_19
   91. S14_19_2
   92. S14_20
   93. S14_20_SMT_0
   94. S14_20_SMT_1
   95. S14_20_SMT_2
   96. S14_20_SMT_3
   97. S14_20_SMT_4
   98. ENA_SURVDATE
   99. ENA_DOB
  100. ENA_DOBM
  101. ENA_WEIGHT
  102. ENA_HEIGHT
  103. E0A_EDEMA
  104. ENA_MUAC
  105. WAZ_NCHS
  106. HAZ_NCHS
  107. WHZ_NCHS
  108. WAZ_WHO
  109. HAZ_WHO
  110. WHZ_WHO
  111. BMIZ_WHO
  112. WAM_NCHS
  113. HAM_NCHS
  114. WHM_NCHS
  115. Flag_NCHS
  116. Flag_WHO
  117. MUACZ_age
  118. Height_Age_WHO
  119. MUACZ_Ht
  120. Age_cat_child
  121. Age_6_59_5cat
  122. AgeCat
  123. MAD_FBF1_V01
  124. MAD_FBF1_V02
  125. MAD_FBF1_V03
  126. MAD_FBF1_V04
  127. MAD_FBF1_V05
  128. MAD_FBF1_V06
  129. MAD_FBF1_V07
  130. MAD_FBF1_V08
  131. MAD_FBF1_V09
  132. MAD_FBF1_CDDS
  133. MAD_FBF1_CMMFS
  134. MAD_FBF1_CMAD
  135. MAD_FBF4_V01
  136. MAD_FBF4_V02
  137. MAD_FBF4_V03
  138. MAD_FBF4_V04
  139. MAD_FBF4_V05
  140. MAD_FBF4_V06
  141. MAD_FBF4_V07
  142. MAD_FBF4_V08
  143. MAD_FBF4_V09
  144. MAD_FBF4_CDDS
  145. MAD_FBF4_CMMFS
  146. MAD_FBF4_CMAD
  147. WAZ_WHO_Cat
  148. WHZ_WHO_Cat
  149. HAZ_WHO_Cat
  150. Global_Stunting
  151. Global_Wasting
  152. Global_Underweight
  153. Separator_Two
  154. Spliter_Two
  155. S13_01_3
  156. S13_01_4
  157. S13_01_5
  158. S13_02
  159. S13_03
  160. S13_03_2
  161. S13_03_3
  162. S13_04
  163. S13_05
  164. S13_05_2
  165. S13_06
  166. S13_07
  167. S13_08
  168. S13_08_2
  169. S13_08_3
  170. S13_09
  171. S13_10
  172. S13_10_2
  173. S13_11
  174. S13_11_2
  175. S13_12
  176. S13_13
  177. S13_13_2
  178. S13_14
  179. S13_14_SMT_1
  180. S13_14_SMT_2
  181. S13_14_SMT_3
  182. S13_14_SMT_4
  183. S13_14_SMT_5
  184. S13_14_SMT_6
  185. S13_14_SMT_88
  186. S13_14_2
  187. S13_15
  188. S13_16
  189. Muac_cat
  190. AS13_17
  191. BS13_17
  192. CS13_17
  193. DS13_17
  194. ES13_17
  195. GS13_17
  196. HS13_17
  197. IS13_17
  198. JS13_17
  199. KS13_17
  200. LS13_17
  201. MS13_17
  202. NS13_17
  203. OS13_17
  204. PS13_17
  205. QS13_17
  206. Cereals_MDDW
  207. Pulses_MDDW
  208. Nuts_MDDW
  209. Milk_MDDW
  210. Meat_MDDW
  211. Eggs_MDDW
  212. GreenVeg_MDDW
  213. VitA_MDDW
  214. OtherVeg_MDDW
  215. OtherFruit_MDDW
  216. Tot_MDDW
  217. MDDWLess5
  218. Age_cat_child_REC

In [10]:
# ============================================
# CHECK ALL OUR CHOSEN FEATURES
# ============================================

features_to_check = [
    # Location
    'S0_C_Prov', 'UrbanRural', 'S0_E_Livezone',

    # Poverty
    'WI_cat', 'Ubudehe', 'FS_final',

    # Household
    'VHHSize',

    # Child
    'S13_02', 'Age_cat_child',

    # Mother
    'S13_01_4',

    # Feeding (6-59 months)
    'MAD_FBF4_CDDS', 'MAD_FBF4_CMMFS', 'MAD_FBF4_CMAD',

    # Diet
    'Tot_MDDW', 'Meat_MDDW', 'Eggs_MDDW', 'GreenVeg_MDDW',

    # Health
    'S13_06', 'S13_07'
]

print("=" * 60)
for col in features_to_check:
    print(f"\n📌 {col}")
    print(f"   Type    : {df_child[col].dtype}")
    print(f"   Nulls   : {df_child[col].isna().sum()}")
    print(f"   Values  : {df_child[col].dropna().unique()[:6]}")
print("=" * 60)

============================================================

📌 S0_C_Prov
   Type    : category
   Nulls   : 0
   Values  : ['Northern province', 'Eastern province', 'Southern province', 'Western province', 'Kigali city']
Categories (5, object): ['Eastern province', 'Kigali city', 'Northern province', 'Southern province',
                         'Western province']

📌 UrbanRural
   Type    : category
   Nulls   : 0
   Values  : ['Rural', 'Urban']
Categories (2, object): ['Rural', 'Urban']

📌 S0_E_Livezone
   Type    : category
   Nulls   : 0
   Values  : ['East Congo-Nile Highland Subsistence Farming ..., 'Eastern Semi-Arid Agropastoral Zone', 'Central Plateau Cassava and Coffee Zone', 'Lake Kivu Coffee Zone', 'Eastern Agropastoral Zone', 'Northern Highland Beans and Wheat Zone']
Categories (13, object): ['Bugesera Cassava Zone', 'Central Plateau Cassava and Coffee Zone',
                          'Central-Northern Highland Irish Potato, Beans..., 'East Congo-Nile Highland Subsistence Farming ..., ...,
                          'Northern Highland Beans and Wheat Zone', 'Northwest Volcanic Irish Potato Zone',
                          'Southeastern Plateau Banana Zone', 'West Congo-Nile Crest Tea Zone']

📌 WI_cat
   Type    : category
   Nulls   : 0
   Values  : ['Wealthy', 'Poor', 'Poorest', 'Medium', 'Wealthiest']
Categories (5, object): ['Medium', 'Poor', 'Poorest', 'Wealthiest', 'Wealthy']

📌 Ubudehe
   Type    : category
   Nulls   : 0
   Values  : ['[3] Category three', '[2] Category two', '[1] Category one', '[0] Don't know', '[88] Not assigned yet', '[4] Category four']
Categories (6, object): ['[0] Don't know', '[1] Category one', '[2] Category two',
                         '[3] Category three', '[4] Category four', '[88] Not assigned yet']

📌 FS_final
   Type    : category
   Nulls   : 0
   Values  : ['Food secure', 'Moderately food insecure', 'Marginally food secure', 'Severely food insecure']
Categories (4, object): ['Food secure', 'Marginally food secure', 'Moderately food insecure',
                         'Severely food insecure']

📌 VHHSize
   Type    : float64
   Nulls   : 0
   Values  : [223. 152. 175.  60. 151.  79.]

📌 S13_02
   Type    : category
   Nulls   : 863
   Values  : ['Yes']
Categories (1, object): ['Yes']

📌 Age_cat_child
   Type    : category
   Nulls   : 1013
   Values  : ['54-59 months', '48-53 months', '42-47 months', '36-41 months', '30-35 months', '24-29 months']
Categories (10, object): ['12-17 months', '18-23 months', '24-29 months', '30-35 months', ...,
                          '48-53 months', '54-59 months', '6-11 months', '<6 months']

📌 S13_01_4
   Type    : category
   Nulls   : 863
   Values  : ['No', 'Yes (both read and write)', 'Yes (read only)']
Categories (3, object): ['No', 'Yes (both read and write)', 'Yes (read only)']

📌 MAD_FBF4_CDDS
   Type    : category
   Nulls   : 4696
   Values  : ['Yes', 'No']
Categories (2, object): ['No', 'Yes']

📌 MAD_FBF4_CMMFS
   Type    : category
   Nulls   : 4696
   Values  : ['Yes', 'No']
Categories (2, object): ['No', 'Yes']

📌 MAD_FBF4_CMAD
   Type    : category
   Nulls   : 4696
   Values  : ['Yes', 'No']
Categories (2, object): ['No', 'Yes']

📌 Tot_MDDW
   Type    : float64
   Nulls   : 863
   Values  : [4. 2. 3. 1. 6. 5.]

📌 Meat_MDDW
   Type    : float64
   Nulls   : 863
   Values  : [0. 1.]

📌 Eggs_MDDW
   Type    : float64
   Nulls   : 863
   Values  : [0. 1.]

📌 GreenVeg_MDDW
   Type    : float64
   Nulls   : 863
   Values  : [1. 0.]

📌 S13_06
   Type    : category
   Nulls   : 886
   Values  : ['No', 'Yes']
Categories (2, object): ['No', 'Yes']

📌 S13_07
   Type    : category
   Nulls   : 2831
   Values  : ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
============================================================

In [11]:
# Check S13_02 surrounding columns for sex
sex_cols = df_child.iloc[:, 155:170]  # columns around S13_02
for col in sex_cols.columns:
    print(f"{col}: {df_child[col].dropna().unique()[:5]}")

S13_01_3: [39. 30. 37. 43. 35.]
S13_01_4: ['No', 'Yes (both read and write)', 'Yes (read only)']
Categories (3, object): ['No', 'Yes (both read and write)', 'Yes (read only)']
S13_01_5: ['No school', 'Some/still primary', 'Vocational school', 'Completed secondary', 'Completed primary']
Categories (9, object): ['Completed primary', 'Completed secondary', 'Completed university',
                         'Don't know', ..., 'Some/still primary', 'Some/still secondary',
                         'Some/still university', 'Vocational school']
S13_02: ['Yes']
Categories (1, object): ['Yes']
S13_03: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S13_03_2: ['Injectables', 'Cervical mucus', 'Beads', 'Implants', 'Pills']
Categories (9, object): ['Beads', 'Cervical mucus', 'Condom', 'IUD', ..., 'Injectables',
                         'No in need yet', 'Other', 'Pills']
S13_03_3: []
S13_04: ['Yes (was pregnant and gave brith)', 'Never gave birth but been pregnant', 'Never been pregnant']
Categories (3, object): ['Never been pregnant', 'Never gave birth but been pregnant',
                         'Yes (was pregnant and gave brith)']
S13_05: ['Neither', 'Lactating only', 'Pregnant only', 'Both (pregnant and lactating)', 'Don't know']
Categories (5, object): ['Both (pregnant and lactating)', 'Don't know', 'Lactating only', 'Neither', 'Pregnant only']
S13_05_2: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S13_06: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S13_07: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
S13_08: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
S13_08_2: ['Public health care provider (at health center..., 'Private health care provider (at health cente..., 'Other (speficy)']
Categories (3, object): ['Other (speficy)', 'Private health care provider (at health cente...,
                         'Public health care provider (at health center...]
S13_08_3: [3. 5. 4. 2. 6.]

In [12]:
# Compare FBF1 vs FBF4 missing values
print("MAD_FBF1 nulls:")
print(f"  CDDS : {df_child['MAD_FBF1_CDDS'].isna().sum()}")
print(f"  CMMFS: {df_child['MAD_FBF1_CMMFS'].isna().sum()}")
print(f"  CMAD : {df_child['MAD_FBF1_CMAD'].isna().sum()}")

print("\nMAD_FBF4 nulls:")
print(f"  CDDS : {df_child['MAD_FBF4_CDDS'].isna().sum()}")
print(f"  CMMFS: {df_child['MAD_FBF4_CMMFS'].isna().sum()}")
print(f"  CMAD : {df_child['MAD_FBF4_CMAD'].isna().sum()}")

MAD_FBF1 nulls:
  CDDS : 4696
  CMMFS: 4696
  CMAD : 4696

MAD_FBF4 nulls:
  CDDS : 4696
  CMMFS: 4696
  CMAD : 4696

In [13]:
# Check anthropometry section for sex column
print("Checking columns 98-125:\n")
for col in df_child.columns[98:125]:
    unique_vals = df_child[col].dropna().unique()[:5]
    nulls = df_child[col].isna().sum()
    print(f"{col:20s} | nulls: {nulls:4d} | values: {unique_vals}")

Checking columns 98-125:

ENA_SURVDATE         | nulls:  826 | values: <DatetimeArray>
['2018-03-24 00:00:00', '2018-03-27 00:00:00', '2018-03-04 00:00:00',
 '2018-03-09 00:00:00', '2018-03-21 00:00:00']
Length: 5, dtype: datetime64[ns]
ENA_DOB              | nulls:  826 | values: <DatetimeArray>
['2013-03-23 00:00:00', '2013-03-24 00:00:00', '2013-03-27 00:00:00',
 '2013-03-06 00:00:00', '2013-03-11 00:00:00']
Length: 5, dtype: datetime64[ns]
ENA_DOBM             | nulls:  826 | values: [60.02 59.99 59.93 59.89 59.86]
ENA_WEIGHT           | nulls:  826 | values: [19.6 16.1 16.  15.1 14.3]
ENA_HEIGHT           | nulls:  826 | values: [111.9 100.5 101.6 104.  101.5]
E0A_EDEMA            | nulls:  826 | values: ['No']
Categories (1, object): ['No']
ENA_MUAC             | nulls:  826 | values: [158. 164. 153. 144. 156.]
WAZ_NCHS             | nulls:  826 | values: [ 0.384 -0.81  -0.861 -1.324 -1.211]
HAZ_NCHS             | nulls:  826 | values: [ 0.427 -1.782 -1.533 -0.983 -1.826]
WHZ_NCHS             | nulls:  826 | values: [ 0.173  0.36   0.121 -0.932 -0.038]
WAZ_WHO              | nulls:  826 | values: [ 0.489 -0.852 -0.896 -1.305 -0.967]
HAZ_WHO              | nulls:  826 | values: [ 0.415 -1.876 -1.644 -1.133 -1.819]
WHZ_WHO              | nulls:  826 | values: [ 0.226  0.506  0.21  -0.944  0.237]
BMIZ_WHO             | nulls:  826 | values: [ 0.34   0.43   0.149 -0.943  0.322]
WAM_NCHS             | nulls:  826 | values: [104.9   91.15  90.58  85.53  86.28]
HAM_NCHS             | nulls:  826 | values: [101.8   92.73  93.75  95.99  92.37]
WHM_NCHS             | nulls:  826 | values: [101.7  103.9  101.3   91.75  99.67]
Flag_NCHS            | nulls:    0 | values: ['' 'HAZ' 'WAZ, HAZ' 'WHZ' 'WAZ, HAZ, WHZ']
Flag_WHO             | nulls:    0 | values: ['' 'HAZ' 'WAZ, HAZ' 'WAZ, WHZ' 'HAZ, WHZ']
MUACZ_age            | nulls:  827 | values: [-0.694 -0.292 -1.042 -1.635 -0.83 ]
Height_Age_WHO       | nulls:  826 | values: [64.05 44.3  46.11 50.18 44.8 ]
MUACZ_Ht             | nulls:  881 | values: [-0.192  0.172 -0.751 -1.336 -0.274]
Age_cat_child        | nulls: 1013 | values: ['54-59 months', '48-53 months', '42-47 months', '36-41 months', '30-35 months']
Categories (10, object): ['12-17 months', '18-23 months', '24-29 months', '30-35 months', ...,
                          '48-53 months', '54-59 months', '6-11 months', '<6 months']
Age_6_59_5cat        | nulls: 1013 | values: ['48-59', '36-47', '24-35', '12-23', '6-11']
Categories (6, object): [0.0, '12-23', '24-35', '36-47', '48-59', '6-11']
AgeCat               | nulls: 4696 | values: ['18-23 months', '12-17 months', '6-11 months']
Categories (3, object): ['12-17 months', '18-23 months', '6-11 months']
MAD_FBF1_V01         | nulls: 4696 | values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
MAD_FBF1_V02         | nulls: 4696 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']

In [14]:
# Check Section 14 columns (22-97)
print("Checking S14 columns:\n")
for col in df_child.columns[22:55]:
    unique_vals = df_child[col].dropna().unique()[:5]
    nulls = df_child[col].isna().sum()
    print(f"{col:20s} | nulls: {nulls:4d} | values: {unique_vals}")

Checking S14 columns:

S14_01               | nulls:    0 | values: [6. 8. 4. 5. 3.]
S14_01_3             | nulls:    0 | values: [1.35833760e+10 1.35834624e+10 1.35837216e+10 1.35829440e+10
 1.35819072e+10]
S14_01_4             | nulls:    0 | values: [59.99 59.96 59.92 59.89 59.86]
S14_01_4_CAT         | nulls:    0 | values: ['Include (6-60m)', 'Exclude (<6m)']
Categories (2, object): ['Exclude (<6m)', 'Include (6-60m)']
S14_01_5             | nulls:    0 | values: ['Male', 'Female']
Categories (2, object): ['Female', 'Male']
S14_02               | nulls:    0 | values: ['Grandmother', 'Mother', 'Father', 'Homemaid', 'Other relationship']
Categories (6, object): ['Close family relative', 'Father', 'Grandmother', 'Homemaid', 'Mother',
                         'Other relationship']
S14_03               | nulls:    0 | values: ['Grandmother', 'Mother', 'Father', 'Homemaid', 'Other relationship']
Categories (6, object): ['Close family relative', 'Father', 'Grandmother', 'Homemaid', 'Mother',
                         'Other relationship']
S14_04               | nulls:    0 | values: ['Doesn't live in this household', '${S1C21}', '${S1C20}', '${S1C24}', '${S1C22}']
Categories (14, object): ['${S1C20}', '${S1C21}', '${S1C22}', '${S1C23}', ..., '${S1C31}', '${S1C32}',
                          'Deceased', 'Doesn't live in this household']
S14_05               | nulls:    0 | values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
S14_06               | nulls:  854 | values: [3.9 3.3 3.6 4.3 4. ]
S14_07               | nulls:  788 | values: ['Yes', 'No', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
S14_08               | nulls: 1433 | values: ['Yes', 'No', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
S14_09               | nulls:  788 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_10               | nulls:  788 | values: ['No', 'Yes', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
S14_11               | nulls:  788 | values: ['No', 'Yes', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
S14_11_2             | nulls: 5867 | values: ['Nothing was done', 'Was given other diarrhea treatment', 'Was given homemade or packaged (ReSoMal) oral..., 'Was zinc supplement given along with the home..., 'Was given more food']
Categories (9, object): ['Nothing was done', 'Was frequently breastfed', 'Was given RUTF',
                         'Was given clean safe drinking water', ..., 'Was given more drinks', 'Was given more food',
                         'Was given other diarrhea treatment', 'Was zinc supplement given along with the home...]
S14_11_2_SMT_1       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_2       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_3       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_4       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_5       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_6       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_7       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_8       | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_SMT_88      | nulls:    0 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
S14_11_2_2           | nulls:    0 | values: ['' 'Yahawe imiti yakinyarwanda' 'Umubirizi'
 'Bamuvugutiye umubirizi kuko nta mutuel bagira.' 'I MIT I YA KINYARWANDA']
S14_12               | nulls: 2490 | values: ['Community health care worker', 'Traditional', 'Staff at health facility', 'None']
Categories (4, object): ['Community health care worker', 'None', 'Staff at health facility', 'Traditional']
S14_13               | nulls:  788 | values: ['Yes', 'No', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
S14_14               | nulls:  788 | values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
AS14_15              | nulls: 4167 | values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
AS14_15_2            | nulls: 6549 | values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
AS14_15_3            | nulls: 4173 | values: ['Less than 1 hour', 'Between 1 -23 hours', '24 hours or more', 'Don't remember']
Categories (4, object): ['24 hours or more', 'Between 1 -23 hours', 'Don't remember',
                         'Less than 1 hour']
BS14_15              | nulls: 4175 | values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']

In [15]:
# Check the remaining S14 columns we are unsure about
cols_to_check = ['S14_05', 'S14_06', 'S14_07',
                 'S14_09', 'S14_10', 'S14_12',
                 'S14_13', 'S14_14']

print("Checking uncertain S14 columns:\n")
for col in cols_to_check:
    nulls = df_child[col].isna().sum()
    vals = df_child[col].dropna().unique()[:5]
    count = df_child[col].value_counts().head(3).to_dict()
    print(f"📌 {col}")
    print(f"   Nulls : {nulls}")
    print(f"   Values: {vals}")
    print(f"   Counts: {count}")
    print()

Checking uncertain S14 columns:

📌 S14_05
   Nulls : 0
   Values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
   Counts: {'Yes': 6474, 'No': 262}

📌 S14_06
   Nulls : 854
   Values: [3.9 3.3 3.6 4.3 4. ]
   Counts: {3.0: 818, 3.5: 647, 3.2: 564}

📌 S14_07
   Nulls : 788
   Values: ['Yes', 'No', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
   Counts: {'Yes': 5209, 'No': 680, "Don't know": 59}

📌 S14_09
   Nulls : 788
   Values: ['No', 'Yes']
Categories (2, object): ['No', 'Yes']
   Counts: {'No': 2986, 'Yes': 2962}

📌 S14_10
   Nulls : 788
   Values: ['No', 'Yes', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
   Counts: {'Yes': 3833, 'No': 2114, "Don't know": 1}

📌 S14_12
   Nulls : 2490
   Values: ['Community health care worker', 'Traditional', 'Staff at health facility', 'None']
Categories (4, object): ['Community health care worker', 'None', 'Staff at health facility', 'Traditional']
   Counts: {'Staff at health facility': 2133, 'None': 1392, 'Community health care worker': 375}

📌 S14_13
   Nulls : 788
   Values: ['Yes', 'No', 'Don't know']
Categories (3, object): ['Don't know', 'No', 'Yes']
   Counts: {'Yes': 5198, 'No': 734, "Don't know": 16}

📌 S14_14
   Nulls : 788
   Values: ['Yes', 'No']
Categories (2, object): ['No', 'Yes']
   Counts: {'Yes': 4489, 'No': 1459}

In [16]:
# ============================================
# CREATE OUR WORKING DATASET
# ============================================

selected_columns = [
    # Target
    'Global_Stunting',

    # Location
    'S0_C_Prov', 'UrbanRural', 'S0_E_Livezone',

    # Economic Status
    'WI_cat', 'Ubudehe', 'FS_final',

    # Child
    'S14_01_5', 'ENA_DOBM', 'S14_07', 'S14_09',
    'S14_10', 'S14_13', 'S14_14',

    # Mother
    'S13_01_3', 'S13_01_5', 'S13_03', 'S13_05',

    # Diet & Feeding
    'S14_06', 'Tot_MDDW', 'Meat_MDDW',
    'Eggs_MDDW', 'GreenVeg_MDDW'
]

# Create working dataset
df = df_child[selected_columns].copy()

print("✅ Working dataset created!")
print(f"\nShape: {df.shape}")
print(f"Rows    : {df.shape[0]} children")
print(f"Columns : {df.shape[1]} variables")

✅ Working dataset created!

Shape: (6736, 23)
Rows    : 6736 children
Columns : 23 variables

In [17]:
# ============================================
# RENAME COLUMNS TO MEANINGFUL NAMES
# ============================================

df = df.rename(columns={
    # Target
    'Global_Stunting'  : 'stunting',

    # Location
    'S0_C_Prov'        : 'province',
    'UrbanRural'       : 'urban_rural',
    'S0_E_Livezone'    : 'livelihood_zone',

    # Economic
    'WI_cat'           : 'wealth_index',
    'Ubudehe'          : 'ubudehe_category',
    'FS_final'         : 'food_security',

    # Child
    'S14_01_5'         : 'child_sex',
    'ENA_DOBM'         : 'child_age_months',
    'S14_07'           : 'vaccinated',
    'S14_09'           : 'had_diarrhea',
    'S14_10'           : 'vitamin_a',
    'S14_13'           : 'mosquito_net',
    'S14_14'           : 'deworming',

    # Mother
    'S13_01_3'         : 'mother_age',
    'S13_01_5'         : 'mother_education',
    'S13_03'           : 'breastfeeding',
    'S13_05'           : 'mother_preg_lact',

    # Diet
    'S14_06'           : 'meals_per_day',
    'Tot_MDDW'         : 'diet_diversity_score',
    'Meat_MDDW'        : 'ate_meat',
    'Eggs_MDDW'        : 'ate_eggs',
    'GreenVeg_MDDW'    : 'ate_vegetables'
})

print("✅ Columns renamed successfully!")
print("\nNew column names:")
for col in df.columns:
    print(f"   {col}")

✅ Columns renamed successfully!

New column names:
   stunting
   province
   urban_rural
   livelihood_zone
   wealth_index
   ubudehe_category
   food_security
   child_sex
   child_age_months
   vaccinated
   had_diarrhea
   vitamin_a
   mosquito_net
   deworming
   mother_age
   mother_education
   breastfeeding
   mother_preg_lact
   meals_per_day
   diet_diversity_score
   ate_meat
   ate_eggs
   ate_vegetables

In [18]:
# ============================================
# PREVIEW OUR CLEAN WORKING DATASET
# ============================================

print("=" * 60)
print("OUR WORKING DATASET — PREVIEW")
print("=" * 60)

# Show first 5 rows
print("\nFirst 5 rows:")
df.head()

============================================================
OUR WORKING DATASET — PREVIEW
============================================================

First 5 rows:

,stunting,province,urban_rural,livelihood_zone,wealth_index,ubudehe_category,food_security,child_sex,child_age_months,vaccinated,...,deworming,mother_age,mother_education,breastfeeding,mother_preg_lact,meals_per_day,diet_diversity_score,ate_meat,ate_eggs,ate_vegetables
0,No stunted,Northern province,Rural,East Congo-Nile Highland Subsistence Farming Zone,Wealthy,[3] Category three,Food secure,Male,60.02,Yes,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No stunted,Eastern province,Rural,Eastern Semi-Arid Agropastoral Zone,Poor,[2] Category two,Moderately food insecure,Female,59.99,Yes,...,Yes,39.0,No school,No,Neither,3.9,4.0,0.0,0.0,1.0
2,No stunted,Southern province,Rural,Central Plateau Cassava and Coffee Zone,Poorest,[3] Category three,Moderately food insecure,Female,59.99,No,...,No,30.0,Some/still primary,No,Lactating only,3.3,2.0,0.0,0.0,0.0
3,NaN,Western province,Rural,Lake Kivu Coffee Zone,Medium,[1] Category one,Moderately food insecure,Female,NaN,NaN,...,NaN,37.0,Some/still primary,No,Lactating only,NaN,4.0,0.0,0.0,1.0
4,No stunted,Southern province,Rural,Central Plateau Cassava and Coffee Zone,Wealthy,[3] Category three,Marginally food secure,Female,59.93,Yes,...,Yes,43.0,Vocational school,No,Pregnant only,3.6,2.0,0.0,0.0,0.0

In [19]:
# ============================================
# QUICK SUMMARY OF EACH COLUMN
# ============================================

print("COLUMN SUMMARY\n")
print(f"{'Column':<25} {'Type':<12} {'Nulls':<8} {'Unique Values'}")
print("-" * 70)
for col in df.columns:
    dtype = str(df[col].dtype)
    nulls = df[col].isna().sum()
    n_unique = df[col].nunique()
    print(f"{col:<25} {dtype:<12} {nulls:<8} {n_unique}")

COLUMN SUMMARY

Column                    Type         Nulls    Unique Values
----------------------------------------------------------------------
stunting                  category     826      2
province                  category     0        5
urban_rural               category     0        2
livelihood_zone           category     0        13
wealth_index              category     0        5
ubudehe_category          category     0        6
food_security             category     0        4
child_sex                 category     0        2
child_age_months          float64      826      1610
vaccinated                category     788      3
had_diarrhea              category     788      2
vitamin_a                 category     788      3
mosquito_net              category     788      3
deworming                 category     788      2
mother_age                float64      863      35
mother_education          category     863      9
breastfeeding             category     863      2
mother_preg_lact          category     886      5
meals_per_day             float64      854      51
diet_diversity_score      float64      863      11
ate_meat                  float64      863      2
ate_eggs                  float64      863      2
ate_vegetables            float64      863      2